version: '3'

services:
  db:
    container_name: app.proyectothera.com.ar_db
    image: mariadb:10
    env_file: docker/production/.env
    logging:
      driver: none
    # restart: unless-stopped
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - default

  web:
    container_name: app.proyectothera.com.ar_web
    image: project-thera/thera-webapp
    build:
      context: .
      dockerfile: docker/production/web/Dockerfile
      args:
        # [Choice] Ruby version: 2, 2.7, 2.7.4
        RUBY_VERSION: 2.7.4
        # [Choice] Node.js version: lts, 16, 14, 12, 10
        NODE_VERSION: "14.19.0-r0"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        UID: 1000
        GID: 1000
    env_file: docker/production/.env
    restart: unless-stopped
    # volumes:
    #   # - web_gems:/usr/local/bundle
    #   - web_log:/usr/local/app/log
    #   # - web_modules:/usr/local/app/node_modules
    #   - web_uploads:/usr/local/app/private/web_uploads
    # command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
    ports:
      - 3000:3000


# volumes:
#   # db_data:
#   # web_gems:
#   web_log:
#   # web_modules:
#   web_uploads:
