version: '3.8'

services:
  web:
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.therawebapp-https.redirectscheme.scheme=https
      - traefik.http.routers.therawebapp-http.entrypoints=http
      - traefik.http.routers.therawebapp-http.rule=Host(`app.proyectothera.com.ar`)
      - traefik.http.routers.therawebapp-http.middlewares=therawebapp-https@docker
      - traefik.http.routers.therawebapp.entrypoints=https
      - traefik.http.routers.therawebapp.rule=Host(`app.proyectothera.com.ar`)
      - traefik.http.routers.therawebapp.tls=true
      - traefik.http.routers.therawebapp.tls.certresolver=heimdallrResolver
      - traefik.docker.network=heimdallr
    networks:
      - heimdallr

networks:
  heimdallr:
    external: true
